const EVENT_TYPES = {
    LEVEL_UP: "LEVEL_UP",
    GUILD_CHANGED: "GUILD_CHANGED",
    PROFESSION_LEARNED: "PROFESSION_LEARNED",
    RECIPE_LEARNED: "RECIPE_LEARNED",
    EQUIPMENT_CHANGED: "EQUIPMENT_CHANGED",
};

module.exports = EVENT_TYPES;